export const TOKENS = {
  allowedChannelId: Symbol("allowedChannelId"),
  adminUserIds: Symbol("adminUserIds"),
  createId: Symbol("createId"),
  database: Symbol("database"),
  env: Symbol("env"),
  fetch: Symbol("fetch"),
  gameHistory: Symbol("gameHistory"),
  leaderboardList: Symbol("leaderboardList"),
  leaderboardListRepository: Symbol("leaderboardListRepository"),
  leaderboardListStorage: Symbol("leaderboardListStorage"),
  now: Symbol("now"),
  sessionRoom: Symbol("sessionRoom"),
  slackBotToken: Symbol("slackBotToken"),
  slackClient: Symbol("slackClient"),
  statisticsRepository: Symbol("statisticsRepository"),
} as const;
